apiVersion: v1
kind: ConfigMap
metadata:
  name: etce-ims-server-configmap
  namespace: inventory-management
data:
  default.json: |
{
  "server": {
    "host": "0.0.0.0",
    "port": 3007,
    "dbConnectionString": "mongodb://localhost:27017/inventory-management"
  }
}
