import { notifications } from "@mantine/notifications";
import {createAsyncThunk, createSlice} from "@reduxjs/toolkit";
import axios from "axios";
import { Keys } from "../Arch/keys";
import { BackendBaseUrl } from "../Arch/Urls";
import { Building } from "../Models/Building";
import { User } from "../Models/User";
import { RootState } from "../Store";

export interface BuildingState{
    buidlings: Building[]
    status: 'idle' | 'loading' | 'failed'
}

const initialState : BuildingState = {
    buidlings: [],
    status: 'idle'
}

export const getBuildingsAsync = createAsyncThunk(
    'getBuildingsAsync',
    async () => {
        const getBuildingsUrl = BackendBaseUrl + "/building/all"
        const data = await axios.get(
            getBuildingsUrl,
            {
                headers: {
                    token: window.localStorage.getItem(Keys.Access_token)
                },
                withCredentials: true
            }
        )
        console.log(data)
        return {buildings: data.data.buildings}
    }
);

export const createBuildingAsync = createAsyncThunk(
    'createBuildingAsync',
    async ({name, address}:{name: string, address: string}) => {
        const createBuildingAsyncUrl = BackendBaseUrl + "/building/create"
        const data = await axios.post(
            createBuildingAsyncUrl,
            {
                name : name,
                address : address
            },
            {
                headers: {
                    token: window.localStorage.getItem(Keys.Access_token)
                },
                withCredentials: true
            }
        )
        console.log(data)
        return data
    }
);

export const deleteBuildingAsync = createAsyncThunk(
    'deleteBuildingAsync',
    async (buildingId: string) => {
        const deleteBuildingAsyncUrl = BackendBaseUrl + "/building/delete"
        console.log(buildingId)
        const data = await axios.post(
            deleteBuildingAsyncUrl,
            {
                buildingId : buildingId
            },
            {
                headers: {
                    token: window.localStorage.getItem(Keys.Access_token)
                },
                withCredentials: true
            }
        )
        console.log(data)
        return data
    }
);



export const buildingsSlice = createSlice({
    name: 'buildingsSlice',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        // Use the PayloadAction type to declare the contents of `action.payload`
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        //createBuildingAsync
        builder
            .addCase(createBuildingAsync.pending, (state, action) => {
                console.log("createBuildingAsync is loading")
            })
            .addCase(createBuildingAsync.fulfilled, (state, action) => {
                console.log("createBuildingAsync is fulfilled")
                notifications.show({
                    title: action.payload.data.success ? "Success" : "Error",
                    message: action.payload.data.message,
                })
            })
            .addCase(createBuildingAsync.rejected, (state, {error}) => {
                console.log("createBuildingAsync is rejected")
            });

        //deleteBuildingAsync
        builder
            .addCase(deleteBuildingAsync.pending, (state, action) => {
                console.log("deleteBuildingAsync is loading")
            })
            .addCase(deleteBuildingAsync.fulfilled, (state, action) => {
                console.log("deleteBuildingAsync is fulfilled")
                notifications.show({
                    title: action.payload.data.success ? "Success" : "Error",
                    message: action.payload.data.message,
                })
            })
            .addCase(deleteBuildingAsync.rejected, (state, {error}) => {
                console.log("deleteBuildingAsync is rejected")
            });
        
        //getBuildingsAsync
        builder
            .addCase(getBuildingsAsync.pending, (state, action) => {
                console.log("getBuildingsAsync is loading")
            })
            .addCase(getBuildingsAsync.fulfilled, (state, action) => {
                console.log("getBuildingsAsync is fulfilled")
                state.buidlings = action.payload.buildings
            })
            .addCase(getBuildingsAsync.rejected, (state, {error}) => {
                console.log("getBuildingsAsync is rejected")
            });
    },
});

export const {  } = buildingsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectBuildings = (state: RootState) => state.buildings;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.


export default buildingsSlice.reducer;